---
- name: Install httpd Pacakge in a single node
  hosts: 172.31.37.86
  become: true # To run as root user
  tasks:
    - name: Install httpd Package
      yum:
        name: httpd
        state: present

    - name: Start httpd service
      service:
        name: httpd
        state: started
        enabled: yes
    
    - name: Copy index.html file
      copy:
        src: /home/ansibleuser/index.html
        dest: /var/www/html/index.html
        